# Form implementation generated from reading ui file 'Student_Reg_Login_Page.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import All_Images
import Menu_Page


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
#NOTHING TO DO WITH THIS CODE, SO DO NOT TEMPER!
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.Bg_Image = QtWidgets.QLabel(parent=self.centralwidget)
        self.Bg_Image.setGeometry(QtCore.QRect(-150, -200, 1920, 1080))
        self.Bg_Image.setText("")
        self.Bg_Image.setPixmap(QtGui.QPixmap(":/Background/Images/Untitled design.png"))
        self.Bg_Image.setScaledContents(True)
        self.Bg_Image.setObjectName("Bg_Image")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(390, 160, 371, 431))
        self.frame.setStyleSheet("background-color: #e6e6ff;\n"
        "border-radius: 10px;\n""")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")

        
#WORKING WITH THE INPUT TEXT OF THE USERNAME 
        self.Username_Edit = QtWidgets.QLineEdit(parent=self.frame)
        self.Username_Edit.setGeometry(QtCore.QRect(102, 170, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.Username_Edit.setFont(font)
        self.Username_Edit.setStyleSheet("background-color:#464a77;\n"
        "color: #e6e6ff;")
        self.Username_Edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Username_Edit.setObjectName("Username_Edit")

        
#WORKING WITH THE INPUT TEXT OF THE PASSWORD 
        self.Password_Edit = QtWidgets.QLineEdit(parent=self.frame)
        self.Password_Edit.setGeometry(QtCore.QRect(102, 220, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.Password_Edit.setFont(font)
        self.Password_Edit.setStyleSheet("background-color:#464a77;\n"
        "color: #e6e6ff;")
        self.Password_Edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Password_Edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Password_Edit.setObjectName("Password_Edit")

#WORKING WITH LOGIN BUTTON 
        self.Login_Button = QtWidgets.QPushButton(parent=self.frame)
        self.Login_Button.setGeometry(QtCore.QRect(160, 270, 75, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)      
        self.Login_Button.setFont(font)
        self.Login_Button.setStyleSheet("background-color:#464a77;\n"
        "color: white")
        self.Login_Button.setObjectName("Login_Button")

#NOTHING TO DO WITH THIS CODE
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(67, 173, 25, 25))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Background/Images/Profile.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(67, 222, 25, 25))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Background/Images/Password.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(130, 30, 131, 131))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Background/Images/img-01.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")

#WORKING WITH STATUS LABEL (TO TELL THE STATUS OF THE LOGIN EITHER A SUCCESS OR FAILED LOGIN ATTEMPT)
        self.Status_Label = QtWidgets.QLabel(parent=self.frame)
        self.Status_Label.setGeometry(QtCore.QRect(180, 300, 91, 16))
        self.Status_Label.setText("")
        self.Status_Label.setObjectName("Status_Label")     
            
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

# CONNECT THE LOGIN BUTTON CLICK EVENT TO THE VALIDATE_LOGIN METHOD
        self.Login_Button.clicked.connect(self.validate_login)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Username_Edit.setPlaceholderText(_translate("MainWindow", "User ID"))
        self.Password_Edit.setPlaceholderText(_translate("MainWindow", "Password"))
        self.Login_Button.setText(_translate("MainWindow", "LOGIN"))

#WORKING WITH VALIDATE_LOGIN METHOD/FUNCTION HERE
    def validate_login(self):
        user_id = self.Username_Edit.text()
        password = self.Password_Edit.text()

        if user_id == "HELLO" and password == "1234":
            self.Status_Label.setText("Success")
            self.Status_Label.setStyleSheet("color: green; font-weight: bold;")
            self.Display_Menu_Page()
        else:
            self.Status_Label.setText("Failed")
            self.Status_Label.setStyleSheet("color: red; font-weight: bold;")

#WORKING WITH DISPLAYING THE MENU_PAGE METHOD/FUNCTION HERE
    def Display_Menu_Page(self):
        MainWindow.hide()
        self.window2 = QtWidgets.QMainWindow()
        self.ui2 = Menu_Page.Ui_MainWindow()
        self.ui2.setupUi(self.window2)
        self.window2.show()
            
   
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
